// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDZtx8RHzBVAg-8M1F6PihQyvXa57sOmc',
    appId: '1:577840064903:web:85015b8b5818a17ff14b22',
    messagingSenderId: '577840064903',
    projectId: 'enjoyy-b11e0',
    authDomain: 'enjoyy-b11e0.firebaseapp.com',
    storageBucket: 'enjoyy-b11e0.appspot.com',
    measurementId: 'G-QEJ9C41F6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAacZHknBydqRmLTHC43b_VCAI5nUJYNQE',
    appId: '1:577840064903:android:523d16624efbf0cef14b22',
    messagingSenderId: '577840064903',
    projectId: 'enjoyy-b11e0',
    storageBucket: 'enjoyy-b11e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxy8X6AXk4BBVan6URRoTyXFKb35GAUzY',
    appId: '1:577840064903:ios:5ae1f5c4d0997b28f14b22',
    messagingSenderId: '577840064903',
    projectId: 'enjoyy-b11e0',
    storageBucket: 'enjoyy-b11e0.appspot.com',
    iosBundleId: 'com.example.dataa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxy8X6AXk4BBVan6URRoTyXFKb35GAUzY',
    appId: '1:577840064903:ios:5ae1f5c4d0997b28f14b22',
    messagingSenderId: '577840064903',
    projectId: 'enjoyy-b11e0',
    storageBucket: 'enjoyy-b11e0.appspot.com',
    iosBundleId: 'com.example.dataa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDZtx8RHzBVAg-8M1F6PihQyvXa57sOmc',
    appId: '1:577840064903:web:f76235b0f2ceff07f14b22',
    messagingSenderId: '577840064903',
    projectId: 'enjoyy-b11e0',
    authDomain: 'enjoyy-b11e0.firebaseapp.com',
    storageBucket: 'enjoyy-b11e0.appspot.com',
    measurementId: 'G-V008112QCB',
  );
}
